apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-periodic-metrics-reporter
  namespace: min-side
spec:
  envFrom:
    - secret: dittnav-periodic-metrics-reporter-secrets
    - secret: influxdb-credentials
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  ingresses:
    - "https://dittnav-periodic-metrics-reporter.dev.nav.no"
  resources:
    limits:
      cpu: "3"
      memory: 3000Mi
    requests:
      cpu: "1"
      memory: 2560Mi
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      external:
        - host: kafka-schema-registry.nais-q.adeo.no
